http:
  baseURL: "https://honey-service.onrender.com/api/v1"
  prefix: api/v1
  auth:
    privateKey: 96E3CBC46B6F5F73031C6C92A7C2EB98F9CB785C3A075CF43A9FE8819DF45DE5
systemSettings:
  colorPrimary: "#1c7d29"
  commonErrorMessage: "系统出错，请稍后重试."
  oilPrice: 2.2
map:
  oilPrice: 2.2
  aveOild: 0.5
  maxAveSpeed: 74
  minAveSpeed: 12
  minSpeed: 48
  maxSpeed: 80
  no_map_message: "一个报销都不填，怎么成为下一个富婆??"
  homeStart:
    zh_CN: "成都市双流区南湖北路"
    en_US: "China ChengDu"
queryOptions:
  refetchOnReconnect: true
