name: Deploy to Azure web

on:
  push:
    branches: develop
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
      - "**/*.MD"
      - "**/*.md"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [UAT, TEST]
        default: UAT
permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  # CodeScan:
  #   uses: aoda-zhang/shared-devops/.github/workflows/code_scan.yaml@master
  #   with:
  #     app_repository: ${{ github.repository }}

  Build:
    if: github.ref != 'refs/heads/main'
    uses: aoda-zhang/shared-devops/.github/workflows/shared_build.yaml@master
    with:
      app_repository: ${{ github.repository }}
      app_branch: ${{ github.ref }}
      config_folder: honey-web
      currentEnvironment: ${{ inputs.environment || 'UAT'}}
      build_name: honey-web-${{ inputs.environment || 'UAT' }}
      build_script: build:${{ inputs.environment || 'UAT' }}
    secrets:
      PAT: ${{ secrets.PAT }}

  Deploy:
    needs: [Build]
    uses: aoda-zhang/shared-devops/.github/workflows/deploy_azure_web.yaml@master
    with:
      currentEnvironment: ${{ inputs.environment || 'UAT'}}
      build_name: honey-web-${{ inputs.environment || 'UAT' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      AZURE_WEB_TOKEN: ${{ secrets.AZURE_UAT_TOKEN }}
